export const contacts = [
  {
    id: "ba-llb-part-4-sec-b",
    name: "BA.LL.B Part 4 Sec B",
    lastMessage: "You were added",
    time: "01-12-2022",
    unreadCount: 0,
    avatar: "👥",
    type: "group",
    isOnline: false,
  },
  {
    id: "ba-llb-3rd-year",
    name: "BA.LL.B 3rd Year",
    lastMessage: "~Rohit changed their phone number",
    time: "22-10-2023",
    unreadCount: 0,
    avatar: "📚",
    type: "group",
    isOnline: false,
  },
  {
    id: "legal-history-bill-2nd",
    name: "Legal History Bill - 2nd Year",
    lastMessage: "~Ananya changed their phone number",
    time: "22-10-2023",
    unreadCount: 0,
    avatar: "⚖️",
    type: "group",
    isOnline: false,
  },
  {
    id: "sociology-2nd-year",
    name: "Sociology 2nd Year",
    lastMessage: "~Pooja changed their phone number",
    time: "22-10-2023",
    unreadCount: 0,
    avatar: "📊",
    type: "group",
    isOnline: false,
  },
  {
    id: "rahul-sharma",
    name: "Rahul Sharma",
    lastMessage: "Kya haal hai? 😄",
    time: "10:30 AM",
    unreadCount: 2,
    avatar: "👨",
    type: "individual",
    isOnline: true,
  },
  {
    id: "priya-singh",
    name: "Priya Singh",
    lastMessage: "Kal milte hain, chai pe charcha ☕",
    time: "Yesterday",
    unreadCount: 0,
    avatar: "👩",
    type: "individual",
    isOnline: false,
  },
  {
    id: "amit-kumar",
    name: "Amit Kumar",
    lastMessage: "Bhai, notes bhej de na 📄",
    time: "2:45 PM",
    unreadCount: 1,
    avatar: "🧑",
    type: "individual",
    isOnline: true,
  },
  {
    id: "study-group-main",
    name: "Study Group - Law Finals",
    lastMessage: "Assignment deadline extended 📢",
    time: "Today",
    unreadCount: 5,
    avatar: "📖",
    type: "group",
    isOnline: false,
  },
  {
    id: "neha-verma",
    name: "Neha Verma",
    lastMessage: "Great job in moot court today! 👏",
    time: "11:20 AM",
    unreadCount: 0,
    avatar: "👩‍🎓",
    type: "individual",
    isOnline: false,
  },
  {
    id: "project-team",
    name: "Project Team - Delhi Seminar",
    lastMessage: "Meeting shifted to 4 PM 🕓",
    time: "1:15 PM",
    unreadCount: 3,
    avatar: "🚀",
    type: "group",
    isOnline: false,
  },
];


